USE BankAppDb; GO
IF OBJECT_ID('dbo.Account', 'U') IS NULL
CREATE TABLE Account (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL FOREIGN KEY REFERENCES [User](Id),
    AccountName VARCHAR(100),
    IBAN VARCHAR(34) NOT NULL UNIQUE,
    Currency VARCHAR(3) NOT NULL,
    Balance DECIMAL(18,2) DEFAULT 0,
    AccountType VARCHAR(20) NOT NULL,
    Status VARCHAR(20) DEFAULT 'Active',
    CreatedAt DATETIME2 DEFAULT GETUTCDATE()
);
GO