namespace BankApp.Contracts.Enums;

/// <summary>
/// Represents the delivery channel used for two-factor authentication.
/// </summary>
public enum TwoFactorMethod
{
    /// <summary>
    /// The OTP is delivered to the user's registered email address.
    /// </summary>
    Email,

    /// <summary>
    /// The OTP is generated by a TOTP authenticator app (e.g. Google Authenticator).
    /// </summary>
    Authenticator,

    /// <summary>
    /// The OTP is delivered via SMS to the user's registered phone number.
    /// </summary>
    Phone,
}