namespace BankApp.Domain.Enums;

/// <summary>
/// Represents the delivery channel used for two-factor authentication.
/// </summary>
public enum TwoFactorMethod
{
    /// <summary>
    /// The One Time Password is delivered to the user's registered email address.
    /// </summary>
    Email,

    /// <summary>
    /// The One Time Password is generated by a Time based One Time Password authenticator application (e.g. Google Authenticator).
    /// </summary>
    Authenticator,

    /// <summary>
    /// The One Time Password is delivered via SMS to the user's registered phone number.
    /// </summary>
    Phone,
}