#!/usr/bin/env python3
# Generates .env for Docker Compose. DB password and JWT secret are auto-generated.
# Pass --no-email to skip SMTP prompts and use placeholders.
#
#   python scripts/server/setup-dev-env.py [--no-email] [--force]

import argparse
import base64
import getpass
import secrets
import string
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ENV_FILE = REPO_ROOT / ".env"


def gen_db_password(length: int = 20) -> str:
    """Random password satisfying SQL Server complexity rules."""
    specials = "!@#$%^&*"
    pool = string.ascii_letters + string.digits + specials
    while True:
        pwd = "".join(secrets.choice(pool) for _ in range(length))
        if (
            any(c.isupper() for c in pwd)
            and any(c.islower() for c in pwd)
            and any(c.isdigit() for c in pwd)
            and any(c in specials for c in pwd)
        ):
            return pwd


def gen_jwt_secret() -> str:
    """64-character base64 string from 48 random bytes."""
    return base64.b64encode(secrets.token_bytes(48)).decode()


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate .env for BankApp Docker Compose.")
    parser.add_argument("--no-email", action="store_true", help="Use SMTP placeholders.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing .env.")
    args = parser.parse_args()

    print("\nBankApp.Server — Docker .env setup\n------------------------------------")

    if ENV_FILE.exists() and not args.force:
        print(f"\n[WARN] {ENV_FILE} already exists.")
        if input("         Overwrite? [y/N] ").strip().lower() != "y":
            print("Aborted.")
            sys.exit(0)

    db_password = gen_db_password()
    jwt_secret = gen_jwt_secret()
    print(f"\n[OK] {'DB_SA_PASSWORD':<25} generated ({len(db_password)} chars)")
    print(f"[OK] {'JWT_SECRET':<25} generated ({len(jwt_secret)} chars)")

    if args.no_email:
        smtp_host, smtp_port, smtp_user = "smtp.example.com", "587", "dev@example.com"
        smtp_pass, smtp_from = "placeholder", "dev@example.com"
        print("\n[INFO] SMTP skipped — placeholders written. Email sends will fail and be logged.")
    else:
        print("\nSMTP credentials cannot be generated. Use a Gmail App Password.")
        print("Generate one at: Google Account > Security > 2-Step Verification > App passwords\n")
        smtp_host = input("    EMAIL_SMTP_HOST    (e.g. smtp.gmail.com): ").strip() or "smtp.gmail.com"
        smtp_port = input("    EMAIL_SMTP_PORT    (press Enter for 587): ").strip() or "587"
        smtp_user = input("    EMAIL_SMTP_USER    (Gmail address): ").strip()
        smtp_pass = getpass.getpass("    EMAIL_SMTP_PASS    (App password, input hidden): ")
        smtp_from = input("    EMAIL_FROM_ADDRESS (Enter to reuse SmtpUser): ").strip() or smtp_user

    ENV_FILE.write_text(
        f"# Generated by scripts/server/setup-dev-env.py — do not commit.\n\n"
        f"DB_SA_PASSWORD={db_password}\n"
        f"JWT_SECRET={jwt_secret}\n\n"
        f"EMAIL_SMTP_HOST={smtp_host}\n"
        f"EMAIL_SMTP_PORT={smtp_port}\n"
        f"EMAIL_SMTP_USER={smtp_user}\n"
        f"EMAIL_SMTP_PASS={smtp_pass}\n"
        f"EMAIL_FROM_ADDRESS={smtp_from}\n",
        encoding="utf-8",
    )

    print(f"\n[OK] Written to {ENV_FILE}\n\nNext steps:\n  docker compose up --build\n")


if __name__ == "__main__":
    main()
